### ISSUE TITLE
kubectl trace run fails on CoreOS

### ISSUE THREAD

**Issue by miguelbernadi** [iovisor/kubectl-trace#102]
Our cluster nodes are running CoreOS and upon trying to test this tool we found the following error:

```
Error: failed to start container "kubectl-trace-2056455a-4836-11ea-a279-9078419759fa": Error response from daemon: error while creating mount source path '/usr/src': mkdir /usr/src: read-only file system
```

In CoreOS the main filesystem is read-only. Does the tool need to read/write there? Is it possible to configure it as user to avoid it? I couldn't find mentions in the docs or other issues on how to tackle this.

**Comment by alban** [comment]
I can reproduce the issue on Flatcar Container Linux too. The issue seems to have been introduced by commit 6be420afffca84859d8b3319995422fffb819c31 (#76).

On CoreOS, there is no `/usr/src` but it is not needed: the headers are directly available under `/lib/modules/$(uname -r)/`. The tool does not need to read/write there.

To support both Ubuntu (with `/usr/src`) and CoreOS/Flatcar (without `/usr/src`), I would suggest to mount the host `/usr` under `/usr-host` in the tracerunner container and have a symlink from `/usr-host/src` to `/usr/src`.

I'll give it a try.
