### ISSUE TITLE
RFC: Github Actions?

### ISSUE THREAD

**Issue by dalehamel** [iovisor/kubectl-trace#105]
Github actions is now available and its been enabled for the iovisor github org.

Someone with admin access to this repo can add the QUAY_TOKEN to it like what is been done with travis.

The major advantage of actions over travis that I see are:

- Travis.org seems to be getting aged-out for travis.com
- Github actions offers much more concurrency (up to 20 jobs), so we could test kubectl trace maybe against different versions of k8s, and distros?

WDYT @leodido @fntlnz

**Comment by leodido** [comment]
Total +1 from me.

Let's wait for @fntlnz opinion (but I suppose he will be +1 too) :)

**Comment by leodido** [comment]
BTW I can work on it since I'd like to play a bit with GH actions finally :)

**Comment by dalehamel** [comment]
> BTW I can work on it since I'd like to play a bit with GH actions finally :)

Awesome! I added it to iovisor/bcc and iovisor/bpftrace, so you can check out those workflow files as a starting point. Some things are a little unituitive (eg, checkout action isn't default like on travis), but it's just as flexible as travis I think, and IMO a little nicer.

There is an SSH action you can use to ssh in and debug, which I gotta admin I really love.

We can also automate release actions on tags I think too, so could probable automate the process in docs/release.md to trigger when there is a tagged release?

**Comment by dalehamel** [comment]
to add the QUAY_TOKEN we need someone with more privs in the iovisor org

**Comment by leodido** [comment]
> to add the QUAY_TOKEN we need someone with more privs in the iovisor org

Yup, I know

Thanks for all this idea and all the suggestions, btw :)

**Comment by alban** [comment]
I have a Github action in Inspektor Gadget [here](https://github.com/kinvolk/inspektor-gadget/blob/master/.github/workflows/inspektor-gadget.yml) to build a new container image, push it to a container registry, and build the CLI with that exact image reference, so that the artifact could be downloaded on one's laptop and just try it without fearing to use the wrong tag of the container image. Since kubectl-trace and IG have similar architecture, that could help here. At the moment, my setup only really works with people who have rights on the upstream GitHub organization but that's something that I want to improve (https://github.com/kinvolk/inspektor-gadget/issues/31).

I am interested in testing on different Linux versions & Kubernetes versions too. I wanted to explore the [self hosted runner](https://help.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) but haven't so far. If you find how to set it up, I am interested :)

**Comment by fntlnz** [comment]
I like this idea too!
