### ISSUE TITLE
any plans for getting kubectl-trace to support bcc-tools?

### ISSUE THREAD

**Issue by jdonnelly-apixio** [iovisor/kubectl-trace#112]
hey,

You guys write some really awesome stuff. Are there any plans for getting kubectl-trace to work with the set of tools from https://github.com/iovisor/bcc?

Thanks,
Jon

**Comment by fntlnz** [comment]
You mean using kubectl trace to execute bcc tools in any node? It should be relatively low effort since we already ship bcc.

**Comment by alban** [comment]
@jdonnelly-apixio there is also this project https://github.com/kinvolk/inspektor-gadget/ that uses some of the tools from bcc.

**Comment by adelbertc** [comment]
I may be interested in working on this - @fntlnz it seems if kubectl-trace is already carrying bcc along then for a first iteration we can just support what is provided in [`bcc/tools`](https://github.com/iovisor/bcc/tree/master/tools) and have something like `kubectl trace pod/some-pod --bcc memleak -p $container_pid` ?

**Comment by adelbertc** [comment]
After some glancing it does not seem kubectl-trace carries along bcc but should be easy enough to add to the Docker image.

**Comment by jdonnelly-apixio** [comment]
Yea, think that would be awesome to add so that less knowledgeable users could get benefits from the tool without much effort.

**Comment by fntlnz** [comment]
I agree with everything you wrote @adelbertc - it's worth trying the approach you proposed in my opinion.

**Comment by adelbertc** [comment]
Here is a draft PR, untested, but figured I'd put it up for review. This is my first bit of non-trivial Go code so some stuff may not be super idiomatic, please let me know! https://github.com/iovisor/kubectl-trace/pull/117

**Comment by adelbertc** [comment]
#117 is ready for review! Or at least it works on the tool that motivated me to make this PR 😅 Some more info here: https://github.com/iovisor/kubectl-trace/pull/117#issuecomment-647032001

**Comment by dalehamel** [comment]
as i mentioned in #117 i think we should take this even further, and have a generic "Tracer" backend, so that we can natively support all of the main tracing tools. Most of the logic is duplicated, so we only need to write little bits of tracer-specific things, argument handling, etc.

I think this would help to enforce a design that is a bit more decoupled from bpftrace, and allows for doing all of the leg work of selecting a target, and attaching some tracer to it.

I have use cases for things like:
- I want to run something that is only implemented as a bcc tool, and won't work in bpftrace yet for some reason
- I want to run tcpdump to capture all network traffic going to a pod
- I want to run "perf record" to capture data, which I can upload to something like speedscope or flamescope to visualize
- I want to run "rbspy" to record ruby stack traces with process_vm_readv
- I want to run the bpf-based "rbperf" utility to get stack traces

With each of these tools, we just need a specific handler to pass any user-specified arguments, and build the command to run.

**Comment by leodido** [comment]
Oh saw this right now!

I think we are on the same path @dalehamel.

My comment [here](https://github.com/iovisor/kubectl-trace/pull/117#issuecomment-701186824) should reinforce your thought above.

**Comment by dalehamel** [comment]
As an update, @zqureshi is working on this presently

**Comment by dalehamel** [comment]
Fixed by https://github.com/iovisor/kubectl-trace/pull/161
